import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'de' | 'fr' | 'es' | 'it';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

// Language information for display
export const languageInfo = {
  en: { name: 'English', flag: '🇬🇧' },
  de: { name: 'Deutsch', flag: '🇩🇪' },
  fr: { name: 'Français', flag: '🇫🇷' },
  es: { name: 'Español', flag: '🇪🇸' },
  it: { name: 'Italiano', flag: '🇮🇹' },
};

// Core translations for essential UI elements
const translations = {
  en: {
    'nav.tickets': 'Tickets',
    'nav.winningNumbers': 'Winning Numbers',
    'nav.myTickets': 'My Tickets',
    'nav.help': 'Help',
    'nav.login': 'Login',
    'nav.adminPanel': 'Admin Panel',
    'nav.balance': 'Balance',
    'nav.connectWallet': 'Connect Wallet',
    'hero.title': 'WorldJackpot',
    'hero.subtitle': 'The worldwide lottery jackpot',
    'hero.currentJackpot': 'Current Jackpot',
    'hero.nextDrawing': 'Next Drawing',
    'hero.lastWinningNumbers': 'Last Winning Numbers',
    'hero.playNow': 'Play Now',
    'form.title': 'Submit Ticket',
    'form.description': 'Choose 5 numbers from 1-50 and 2 WorldNumbers from 1-12',
    'form.mainNumbersSelector': '5 out of 50 Main Numbers',
    'sidebar.myStats': 'My Statistics',
    'sidebar.activeTickets': 'Active Tickets',
    'sidebar.maxTickets': 'Maximum tickets per drawing: 10',
    'sidebar.costPerTicket': 'Cost per ticket: €2.00',
    'sidebar.howToPlay': 'How to Play',
    'sidebar.step1': 'Choose 5 numbers from 1-50',
    'sidebar.step2': 'Choose 2 WorldNumbers from 1-12',
    'sidebar.step3': 'Submit your ticket (€2 per play)',
    'sidebar.step4': 'Wait for the drawing',
    'sidebar.nextDrawing': 'Next Drawing',
    'sidebar.cutoffTime': 'Cutoff time: 7:00 PM',
    'sidebar.winningClasses': 'Prize Classes',
    'sidebar.class': 'Class',
    'sidebar.correct': 'Correct',
    'sidebar.moreClasses': '... and 7 more classes',
    'sidebar.currentWinners': 'Current Winners',
    'sidebar.winners': 'Winners',
    'myTickets.title': 'My Tickets',
    'myTickets.subtitle': 'Your personally played lottery tickets and their status',
    'myTickets.totalTickets': 'Total Tickets',
    'myTickets.winners': 'Winners',
    'myTickets.totalStake': 'Total Stake',
    'myTickets.totalWinnings': 'Total Winnings',
    'myTickets.ticketsFrom': 'Tickets from',
    'myTickets.ticketsTotal': 'tickets total',
    'myTickets.ticketNumber': 'Ticket #',
    'myTickets.mainNumbers': 'Main numbers',
    'myTickets.worldNumbers': 'World',
    'myTickets.winner': 'Winner!',
    'myTickets.noWin': 'No win',
    'myTickets.class': 'Class',
    'myTickets.noTickets': 'No tickets available',
    'myTickets.noTicketsUser': 'You haven\'t bought any tickets yet.',
    'myTickets.noTicketsLogin': 'Please log in to see your tickets.',
    'myTickets.buyFirst': 'Buy first ticket',
    'myTickets.info.title': 'Ticket Information',
    'myTickets.info.cost': 'Each ticket costs €2.00',
    'myTickets.info.highlights': 'Green highlighted numbers are matches on winning tickets',
    'myTickets.info.automatic': 'Winnings are automatically credited',
    'myTickets.info.limit': 'Maximum: 10 tickets per drawing',
    'winningNumbers.title': 'Winning Numbers',
    'winningNumbers.subtitle': 'Current winning numbers and your tickets for the drawing',
    'winningNumbers.currentJackpot': 'Current Jackpot',
    'winningNumbers.nextDrawing': 'Next Drawing',
    'winningNumbers.currentWinningNumbers': 'Current Winning Numbers',
    'winningNumbers.drawnOn': 'Drawn on',
    'winningNumbers.mainNumbers': 'Main Numbers',
    'winningNumbers.worldNumbers': 'World Numbers',
    'winningNumbers.winnersByClass': 'Winners by Prize Class',
    'winningNumbers.class': 'Class',
    'winningNumbers.winners': 'Winners',
    'winningNumbers.noDrawing': 'No drawing performed yet',
    'winningNumbers.nextDrawingTime': 'The next drawing will take place on:',
    'winningNumbers.fridayTime': 'Friday, 8:00 PM',
    'winningNumbers.cutoffTime': 'Cutoff time: 7:00 PM',
    'winningNumbers.myTicketsForDrawing': 'My Tickets for Current Drawing',
    'winningNumbers.ticketsForNext': 'tickets for the next drawing',
    'winningNumbers.noTicketsForDrawing': 'No tickets for current drawing',
    'winningNumbers.noTicketsForNext': 'You haven\'t bought any tickets for the next drawing yet.',
    'winningNumbers.buyTicket': 'Buy ticket',
    'winningNumbers.active': 'Active',
    'winningNumbers.loginPrompt': 'Please log in',
    'winningNumbers.loginToSeeTickets': 'To see your tickets for the current drawing, please log in.',
    'winningNumbers.toLogin': 'To login',
    'drawing.title': 'WorldJackpot Drawing',
    'drawing.subtitle': 'Current winning numbers and drawing results',
    'drawing.currentJackpot': 'Current Jackpot',
    'drawing.nextDrawing': 'Next Drawing',
    'drawing.currentWinningNumbers': 'Current Winning Numbers',
    'drawing.drawnOn': 'Drawn on',
    'drawing.mainNumbers': 'Main Numbers',
    'drawing.worldNumbers': 'World Numbers',
    'drawing.winnersByClass': 'Winners by Prize Class',
    'drawing.class': 'Class',
    'drawing.winners': 'Winners',
    'drawing.noDrawing': 'No drawing performed yet',
    'drawing.nextDrawingTime': 'The next drawing will take place on:',
    'drawing.fridayTime': 'Friday, 8:00 PM',
    'drawing.cutoffTime': 'Cutoff time: 7:00 PM',
    'drawing.prizeClasses': 'Prize Classes',
    'drawing.class1': 'Class 1 - JACKPOT',
    'drawing.class1desc': '5 correct + 2 World numbers',
    'drawing.class2': 'Class 2',
    'drawing.class2desc': '5 correct + 1 World number',
    'drawing.class3': 'Class 3',
    'drawing.class3desc': '5 correct + 0 World numbers',
    'drawing.class4': 'Class 4',
    'drawing.class4desc': '4 correct + 2 World numbers',
    'drawing.class5': 'Class 5',
    'drawing.class5desc': '4 correct + 1 World number',
    'drawing.classes612': 'Classes 6-12',
    'drawing.classes612desc': 'Other prize classes',
    'drawing.variousCombinations': 'Various combinations',
    'drawing.chance': 'Chance:',
    'drawing.info.title': 'Drawing Information',
    'drawing.info.schedule': 'Drawings take place every Tuesday and Friday at 8:00 PM',
    'drawing.info.cutoff': 'Cutoff time is 7:00 PM respectively',
    'drawing.info.automatic': 'Winnings are automatically credited to your account',
    'drawing.info.notification': 'For larger winnings, you will be notified by email',
    'admin.title': 'WorldJackpot Admin Panel',
    'admin.subtitle': 'Manage jackpots, drawings and monitor the platform',
    'admin.instructions.title': 'Instructions:',
    'admin.instructions.editJackpot': 'Edit jackpot: Click "Edit jackpot" to change the amount',
    'admin.instructions.startDrawing': 'Start drawing: Use the green "Start drawing" button',
    'admin.instructions.manualNumbers': 'Manual numbers: Optionally enter your own winning numbers',
    'admin.instructions.changes': 'All changes: Are immediately visible on the main page',
    'admin.activeUsers': 'Active Users',
    'admin.soldTickets': 'Sold Tickets',
    'admin.totalRevenue': 'Total Revenue',
    'admin.status': 'Status',
    'admin.drawingPending': 'Drawing pending',
    'admin.ready': 'Ready',
    'admin.jackpotControl': 'Jackpot Control',
    'admin.simulatedJackpot': 'Simulated Jackpot',
    'admin.adminControlled': 'Admin controlled',
    'admin.realJackpot': 'Real Jackpot',
    'admin.percentRevenue': '40% of revenue',
    'admin.displayedJackpot': 'Displayed Jackpot',
    'admin.editJackpot': 'Edit Jackpot',
    'admin.editJackpotAmount': 'Edit Jackpot Amount',
    'admin.newJackpotAmount': 'New Jackpot Amount (€)',
    'admin.warning': 'Warning: This change will be immediately visible on the main page.',
    'admin.confirm': 'Confirm',
    'admin.cancel': 'Cancel',
    'admin.drawingControl': 'Drawing Control',
    'admin.lastWinningNumbers': 'Last Winning Numbers',
    'admin.winnersByClass': 'Winners by Class',
    'admin.noDrawingPerformed': 'No drawing performed',
    'admin.drawingPendingStatus': 'Drawing pending',
    'admin.manualNumbers': 'Manual numbers (optional)',
    'admin.fiveMainNumbers': '5 main numbers (1-50, comma separated)',
    'admin.twoWorldNumbers': '2 World numbers (1-12, comma separated)',
    'admin.startDrawing': 'Start Drawing',
    'admin.drawingInProgress': 'Drawing in progress...',
    'admin.recentTickets': 'Recent Tickets',
    'admin.total': 'total',
    'admin.winnerClass': 'Winner Cl.',
    'admin.intelligentDrawing': 'Intelligent Drawing',
    'admin.intelligentDrawingDesc': 'Optimized drawing to minimize multiple winners',
    'admin.intelligentDrawingEnabled': 'Enabled: Rare number combinations are preferred',
    'admin.intelligentDrawingDisabled': 'Disabled: Regular random drawing',
    'admin.lastAnalysis': 'Last Intelligent Analysis',
    'admin.ticketsAnalyzed': 'tickets analyzed',
    'admin.selectedMainNumbers': 'Selected Main Numbers:',
    'admin.selectedWorldNumbers': 'Selected World Numbers:',
    'admin.rarestNumbers': 'Rarest numbers from analysis',
    'admin.minimizedWinners': 'Minimizes potential winners',
    'admin.intelligentDrawingSuccess': 'Intelligent drawing performed successfully!',
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.loggingIn': 'Logging in...',
    'auth.registering': 'Registering...',
    'footer.subtitle': 'The worldwide lottery jackpot with the best winning chances.',
    'footer.gameInfo': 'Game Information',
    'footer.gameRules': 'Game Rules',
    'footer.prizeClasses': 'Prize Classes',
    'footer.drawingTimes': 'Drawing Times',
    'footer.winningNumbers': 'Winning Numbers',
    'footer.service': 'Service',
    'footer.customerService': 'Customer Service',
    'footer.faq': 'FAQ',
    'footer.contact': 'Contact',
    'footer.legal': 'Legal',
    'footer.imprint': 'Imprint',
    'footer.privacy': 'Privacy',
    'footer.terms': 'Terms',
    'footer.protection': 'Player Protection',
    'footer.rights': '© 2024 WorldJackpot. All rights reserved.',
    'common.mainNumbers': 'Main Numbers',
    'common.worldNumbers': 'World',
    'common.loading': 'Loading...',
    'common.untilNextDrawing': 'until the next drawing',
    'common.drawingOverdue': 'Drawing overdue',
    'common.euro': 'EURO',
    'common.fridayTime': 'Friday, 9:00 PM',
    'common.winningClass': 'Winning Class',
    'common.totalRevenue': 'Total Revenue',
    'common.everyFridayAt21': 'Every Friday at 9:00 PM',
    'common.autoDrawingEnabled': '✅ Auto-drawing is enabled. Drawings take place automatically every Friday at 9:00 PM.',
    'common.autoDrawingDisabled': '⏸️ Auto-drawing is disabled. Drawings must be started manually.',
    'form.fiveMainNumbers': '5 Main numbers (1-50, comma separated)',
    'form.twoWorldNumbers': '2 World numbers (1-12, comma separated)',
    'form.manualNumbersError': 'Manual numbers must contain 5 main numbers and 2 world numbers',
    'admin.jackpotChangeInfo': 'Change the jackpot from 75 million to 10 million euros. This change will be immediately visible on the main page.',
    'hero.worldJackpot': 'WORLD JACKPOT',
    'hero.winningChance': 'Winning chance 1 in 140 million',
    'hero.nextChance': 'Next chance to win',
    'sidebar.totalClasses': 'Total {count} prize classes',
    'admin.displayOverrides': 'Display Overrides',
    'admin.manualTitle': 'Manual Title',
    'admin.manualDate': 'Manual Date',
    'admin.manualTime': 'Manual Time',
    'admin.save': 'Save',
    'admin.reset': 'Reset',
    'admin.overrideNote': 'Note: These changes will override the automatic date/time display on the main page.',
    'admin.manualNumbers': 'Manual numbers (optional)',
    'admin.lastWinningNumbers': 'Last Winning Numbers',
    'admin.winnersByClass': 'Winners by Class',
    'admin.overridesSavedSuccess': 'Display overrides saved successfully!',
    'admin.overridesSaveError': 'Error saving overrides',
    'admin.overridesResetSuccess': 'Display overrides reset!',
    'admin.overridesResetError': 'Error resetting overrides',
    'footer.yourChance': 'World Jackpot - Your chance for the big win',
    'footer.demoArea': 'World Jackpot - Demo Area',
    'footer.liveDrawings': 'World Jackpot - Live Drawings',
    'footer.winningResults': 'World Jackpot - Winning Numbers & Results',
    'footer.adminDashboard': 'World Jackpot - Administrative Dashboard',
    'prizes.winningChance': 'Winning chance: {odds}',
    'drawing.cutoffInfo': 'Cutoff time: 7:00 PM',
    'drawing.cutoffDynamic': 'Cutoff time: {time}',
    'drawing.winnersPerClass': 'Winners by Prize Class',
    'admin.jackpotControl': 'Jackpot Control',
    'admin.simulatedJackpot': 'Simulated Jackpot',
    'admin.adminControlled': 'Admin controlled',
    'admin.realJackpot': 'Real Jackpot',
    'admin.percentRevenue': '40% of revenue',
    'admin.displayedJackpot': 'Displayed Jackpot',
    'admin.editJackpot': 'Edit Jackpot',
    'admin.editJackpotAmount': 'Edit Jackpot Amount',
    'admin.newJackpotAmount': 'New Jackpot Amount (€)',
    'admin.confirm': 'Confirm',
    'admin.cancel': 'Cancel',
    'admin.drawingControl': 'Drawing Control',
    'admin.noDrawingPerformed': 'No drawing performed',
    'admin.drawingPending': 'Drawing pending',
    'admin.ready': 'Ready',
    'admin.startDrawing': 'Start Drawing',
    'admin.drawingInProgress': 'Drawing in progress...',
    'admin.autoDrawing': 'Auto Drawing',
    'admin.automaticDrawing': 'Automatic Drawing',
    'admin.nextDrawing': 'Next Drawing',
    'admin.timeUntilDrawing': 'Time until drawing:',
    'admin.recentTickets': 'Recent Tickets',
    'admin.total': 'total',
    'admin.autoDrawingToggleSuccess': 'Auto-drawing {status}!',
    'admin.autoDrawingToggleError': 'Error toggling auto-drawing',
    'admin.activated': 'activated',
    'admin.deactivated': 'deactivated',
    'form.loginRequired': 'Please log in to submit lottery tickets',
    'form.loginPrompt': 'Log in to submit lottery tickets',
    'form.accountBenefit': 'With an account you can submit up to 10 lottery tickets per drawing',
    'form.maxTicketsError': 'Maximum 10 lottery tickets per drawing allowed',
    'form.completeTicketError': 'Please complete at least one lottery ticket',
    'form.submitSuccess': '{count} lottery ticket(s) successfully submitted!',
    'form.submitError': 'Error submitting lottery tickets',
    'form.ticketNumber': 'Lottery Ticket {number}',
    'form.twoWorldNumbers': '2 out of 12 World Numbers',
    'form.ticketComplete': 'Ticket complete',
    'form.addAnother': 'Add another ticket',
    'form.validTickets': 'Valid tickets: {valid} of {total}',
    'form.totalCost': 'Total cost: {cost}€',
    'form.submitting': 'Submitting...',
    'form.submitTickets': 'Submit {count} ticket(s)',
    'format.timeAt': 'at {time}',
    'admin.user': 'User:',
    'admin.winnerClass': 'Winner Cl.',
  },
  de: {
    'nav.tickets': 'Spielscheine',
    'nav.winningNumbers': 'Gewinnzahlen',
    'nav.myTickets': 'Meine Scheine',
    'nav.help': 'Hilfe',
    'nav.login': 'Anmelden',
    'nav.adminPanel': 'Admin Panel',
    'nav.balance': 'Guthaben',
    'nav.connectWallet': 'Wallet verbinden',
    'hero.title': 'WorldJackpot',
    'hero.subtitle': 'Der weltweite Lotterie-Jackpot',
    'hero.currentJackpot': 'Aktueller Jackpot',
    'hero.nextDrawing': 'Nächste Ziehung',
    'hero.lastWinningNumbers': 'Letzte Gewinnzahlen',
    'hero.playNow': 'Jetzt Spielen',
    'form.title': 'Spielschein abgeben',
    'form.description': 'Wählen Sie 5 Zahlen von 1-50 und 2 WorldZahlen von 1-12',
    'form.mainNumbersSelector': '5 aus 50 Hauptzahlen',
    'sidebar.myStats': 'Meine Statistiken',
    'sidebar.activeTickets': 'Aktive Scheine',
    'sidebar.maxTickets': 'Maximale Scheine pro Ziehung: 10',
    'sidebar.costPerTicket': 'Kosten pro Schein: 2,00€',
    'sidebar.howToPlay': 'So funktioniert\'s',
    'sidebar.step1': 'Wählen Sie 5 Zahlen von 1-50',
    'sidebar.step2': 'Wählen Sie 2 WorldZahlen von 1-12',
    'sidebar.step3': 'Geben Sie Ihren Schein ab (2€ pro Tipp)',
    'sidebar.step4': 'Warten Sie auf die Ziehung',
    'sidebar.nextDrawing': 'Nächste Ziehung',
    'sidebar.cutoffTime': 'Annahmeschluss: 19:00 Uhr',
    'sidebar.winningClasses': 'Gewinnklassen',
    'sidebar.class': 'Klasse',
    'sidebar.correct': 'Richtige',
    'sidebar.moreClasses': '... und 7 weitere Klassen',
    'sidebar.currentWinners': 'Aktuelle Gewinner',
    'sidebar.winners': 'Gewinner',
    'myTickets.title': 'Meine Spielscheine',
    'myTickets.subtitle': 'Ihre persönlich gespielten Lotterie-Scheine und deren Status',
    'myTickets.totalTickets': 'Gesamt Scheine',
    'myTickets.winners': 'Gewinner',
    'myTickets.totalStake': 'Gesamt Einsatz',
    'myTickets.totalWinnings': 'Gewinnsumme',
    'myTickets.ticketsFrom': 'Spielscheine von',
    'myTickets.ticketsTotal': 'Spielscheine insgesamt',
    'myTickets.ticketNumber': 'Schein #',
    'myTickets.mainNumbers': 'Hauptzahlen',
    'myTickets.worldNumbers': 'World',
    'myTickets.winner': 'Gewinner!',
    'myTickets.noWin': 'Kein Gewinn',
    'myTickets.class': 'Klasse',
    'myTickets.noTickets': 'Keine Spielscheine vorhanden',
    'myTickets.noTicketsUser': 'Sie haben noch keine Spielscheine gekauft.',
    'myTickets.noTicketsLogin': 'Melden Sie sich an, um Ihre Spielscheine zu sehen.',
    'myTickets.buyFirst': 'Ersten Spielschein kaufen',
    'myTickets.info.title': 'Spielschein-Informationen',
    'myTickets.info.cost': 'Jeder Spielschein kostet 2,00€',
    'myTickets.info.highlights': 'Grün markierte Zahlen sind Treffer bei Gewinner-Scheinen',
    'myTickets.info.automatic': 'Gewinne werden automatisch gutgeschrieben',
    'myTickets.info.limit': 'Maximale Anzahl: 10 Scheine pro Ziehung',
    'winningNumbers.title': 'Gewinnzahlen',
    'winningNumbers.subtitle': 'Aktuelle Gewinnzahlen und Ihre Scheine für die Ziehung',
    'winningNumbers.currentJackpot': 'Aktueller Jackpot',
    'winningNumbers.nextDrawing': 'Nächste Ziehung',
    'winningNumbers.currentWinningNumbers': 'Aktuelle Gewinnzahlen',
    'winningNumbers.drawnOn': 'Gezogen am',
    'winningNumbers.mainNumbers': 'Hauptzahlen',
    'winningNumbers.worldNumbers': 'WorldZahlen',
    'winningNumbers.winnersByClass': 'Gewinner nach Gewinnklassen',
    'winningNumbers.class': 'Klasse',
    'winningNumbers.winners': 'Gewinner',
    'winningNumbers.noDrawing': 'Noch keine Ziehung durchgeführt',
    'winningNumbers.nextDrawingTime': 'Die nächste Ziehung findet statt am:',
    'winningNumbers.fridayTime': 'Freitag, 20:00 Uhr',
    'winningNumbers.cutoffTime': 'Annahmeschluss: 19:00 Uhr',
    'winningNumbers.myTicketsForDrawing': 'Meine Scheine für aktuelle Ziehung',
    'winningNumbers.ticketsForNext': 'Scheine für die nächste Ziehung',
    'winningNumbers.noTicketsForDrawing': 'Keine Scheine für die aktuelle Ziehung',
    'winningNumbers.noTicketsForNext': 'Sie haben noch keine Scheine für die nächste Ziehung gekauft.',
    'winningNumbers.buyTicket': 'Schein kaufen',
    'winningNumbers.active': 'Aktiv',
    'winningNumbers.loginPrompt': 'Melden Sie sich an',
    'winningNumbers.loginToSeeTickets': 'Um Ihre Scheine für die aktuelle Ziehung zu sehen, melden Sie sich bitte an.',
    'winningNumbers.toLogin': 'Zur Anmeldung',
    'drawing.title': 'WorldJackpot Ziehung',
    'drawing.subtitle': 'Aktuelle Gewinnzahlen und Ziehungsergebnisse',
    'drawing.currentJackpot': 'Aktueller Jackpot',
    'drawing.nextDrawing': 'Nächste Ziehung',
    'drawing.currentWinningNumbers': 'Aktuelle Gewinnzahlen',
    'drawing.drawnOn': 'Gezogen am',
    'drawing.mainNumbers': 'Hauptzahlen',
    'drawing.worldNumbers': 'WorldZahlen',
    'drawing.winnersByClass': 'Gewinner nach Gewinnklassen',
    'drawing.class': 'Klasse',
    'drawing.winners': 'Gewinner',
    'drawing.noDrawing': 'Noch keine Ziehung durchgeführt',
    'drawing.nextDrawingTime': 'Die nächste Ziehung findet statt am:',
    'drawing.fridayTime': 'Freitag, 20:00 Uhr',
    'drawing.cutoffTime': 'Annahmeschluss: 19:00 Uhr',
    'drawing.prizeClasses': 'Gewinnklassen',
    'drawing.class1': 'Klasse 1 - JACKPOT',
    'drawing.class1desc': '5 Richtige + 2 WorldZahlen',
    'drawing.class2': 'Klasse 2',
    'drawing.class2desc': '5 Richtige + 1 WorldZahl',
    'drawing.class3': 'Klasse 3',
    'drawing.class3desc': '5 Richtige + 0 WorldZahlen',
    'drawing.class4': 'Klasse 4',
    'drawing.class4desc': '4 Richtige + 2 WorldZahlen',
    'drawing.class5': 'Klasse 5',
    'drawing.class5desc': '4 Richtige + 1 WorldZahl',
    'drawing.classes612': 'Klassen 6-12',
    'drawing.classes612desc': 'Weitere Gewinnklassen',
    'drawing.variousCombinations': 'Verschiedene Kombinationen',
    'drawing.chance': 'Chance:',
    'drawing.info.title': 'Ziehungshinweise',
    'drawing.info.schedule': 'Ziehungen finden jeden Dienstag und Freitag um 20:00 Uhr statt',
    'drawing.info.cutoff': 'Annahmeschluss ist jeweils um 19:00 Uhr',
    'drawing.info.automatic': 'Gewinne werden automatisch auf Ihr Konto gutgeschrieben',
    'drawing.info.notification': 'Bei größeren Gewinnen werden Sie per E-Mail benachrichtigt',
    'admin.title': 'WorldJackpot Admin Panel',
    'admin.subtitle': 'Verwalten Sie Jackpots, Ziehungen und überwachen Sie die Plattform',
    'admin.instructions.title': 'Anleitung:',
    'admin.instructions.editJackpot': 'Jackpot bearbeiten: Klicken Sie auf "Jackpot bearbeiten" um die Summe zu ändern',
    'admin.instructions.startDrawing': 'Ziehung starten: Verwenden Sie den grünen "Ziehung starten" Button',
    'admin.instructions.manualNumbers': 'Manuelle Zahlen: Optional können Sie eigene Gewinnzahlen eingeben',
    'admin.instructions.changes': 'Alle Änderungen: Werden sofort auf der Hauptseite sichtbar',
    'admin.activeUsers': 'Aktive Nutzer',
    'admin.soldTickets': 'Verkaufte Scheine',
    'admin.totalRevenue': 'Gesamtumsatz',
    'admin.status': 'Status',
    'admin.drawingPending': 'Ziehung ausstehend',
    'admin.ready': 'Bereit',
    'admin.jackpotControl': 'Jackpot-Kontrolle',
    'admin.simulatedJackpot': 'Simulierter Jackpot',
    'admin.adminControlled': 'Von Admin kontrolliert',
    'admin.realJackpot': 'Echter Jackpot',
    'admin.percentRevenue': '40% der Einnahmen',
    'admin.displayedJackpot': 'Angezeigter Jackpot',
    'admin.editJackpot': 'Jackpot bearbeiten',
    'admin.editJackpotAmount': 'Jackpot-Betrag bearbeiten',
    'admin.newJackpotAmount': 'Neuer Jackpot-Betrag (€)',
    'admin.warning': 'Warnung: Diese Änderung wird sofort auf der Hauptseite sichtbar sein.',
    'admin.confirm': 'Bestätigen',
    'admin.cancel': 'Abbrechen',
    'admin.drawingControl': 'Ziehungs-Kontrolle',
    'admin.lastWinningNumbers': 'Letzte Gewinnzahlen',
    'admin.winnersByClass': 'Gewinner nach Klassen',
    'admin.noDrawingPerformed': 'Keine Ziehung durchgeführt',
    'admin.drawingPendingStatus': 'Ziehung ausstehend',
    'admin.manualNumbers': 'Manuelle Zahlen (optional)',
    'admin.fiveMainNumbers': '5 Hauptzahlen (1-50, kommagetrennt)',
    'admin.twoWorldNumbers': '2 WorldZahlen (1-12, kommagetrennt)',
    'admin.startDrawing': 'Ziehung starten',
    'admin.drawingInProgress': 'Ziehung läuft...',
    'admin.recentTickets': 'Letzte Spielscheine',
    'admin.total': 'insgesamt',
    'admin.winnerClass': 'Gewinner Kl.',
    'admin.intelligentDrawing': 'Intelligente Ziehung',
    'admin.intelligentDrawingDesc': 'Optimierte Ziehung zur Minimierung von Mehrfachgewinnen',
    'admin.intelligentDrawingEnabled': 'Aktiviert: Seltene Zahlenkombinationen werden bevorzugt',
    'admin.intelligentDrawingDisabled': 'Deaktiviert: Reguläre Zufallsziehung',
    'admin.lastAnalysis': 'Letzte Intelligente Analyse',
    'admin.ticketsAnalyzed': 'Spielscheine analysiert',
    'admin.selectedMainNumbers': 'Ausgewählte Hauptzahlen:',
    'admin.selectedWorldNumbers': 'Ausgewählte WorldZahlen:',
    'admin.rarestNumbers': 'Seltenste Zahlen aus der Analyse',
    'admin.minimizedWinners': 'Minimiert potentielle Gewinner',
    'admin.intelligentDrawingSuccess': 'Intelligente Ziehung erfolgreich durchgeführt!',
    'auth.login': 'Anmelden',
    'auth.register': 'Registrieren',
    'auth.email': 'E-Mail',
    'auth.password': 'Passwort',
    'auth.confirmPassword': 'Passwort bestätigen',
    'auth.loggingIn': 'Anmelden...',
    'auth.registering': 'Registrieren...',
    'footer.subtitle': 'Der weltweite Lotterie-Jackpot mit den besten Gewinnchancen.',
    'footer.gameInfo': 'Spielinformationen',
    'footer.gameRules': 'Spielregeln',
    'footer.prizeClasses': 'Gewinnklassen',
    'footer.drawingTimes': 'Ziehungszeiten',
    'footer.winningNumbers': 'Gewinnzahlen',
    'footer.service': 'Service',
    'footer.customerService': 'Kundenservice',
    'footer.faq': 'FAQ',
    'footer.contact': 'Kontakt',
    'footer.legal': 'Rechtliches',
    'footer.imprint': 'Impressum',
    'footer.privacy': 'Datenschutz',
    'footer.terms': 'AGB',
    'footer.protection': 'Spielerschutz',
    'footer.rights': '© 2024 WorldJackpot. Alle Rechte vorbehalten.',
    'common.mainNumbers': 'Hauptzahlen',
    'common.worldNumbers': 'World',
    'common.loading': 'Lädt...',
    'common.untilNextDrawing': 'bis zur nächsten Ziehung',
    'common.drawingOverdue': 'Ziehung überfällig',
    'common.euro': 'EURO',
    'common.fridayTime': 'Freitag, 21:00 Uhr',
    'common.winningClass': 'Gewinnklasse',
    'common.totalRevenue': 'Gesamtumsatz',
    'common.everyFridayAt21': 'Jeden Freitag um 21:00 Uhr',
    'common.autoDrawingEnabled': '✅ Auto-Ziehung ist aktiviert. Ziehungen finden automatisch jeden Freitag um 21:00 Uhr statt.',
    'common.autoDrawingDisabled': '⏸️ Auto-Ziehung ist deaktiviert. Ziehungen müssen manuell gestartet werden.',
    'form.fiveMainNumbers': '5 Hauptzahlen (1-50, kommagetrennt)',
    'form.twoWorldNumbers': '2 WorldZahlen (1-12, kommagetrennt)',
    'form.manualNumbersError': 'Manuelle Zahlen müssen 5 Hauptzahlen und 2 Worldzahlen enthalten',
    'admin.jackpotChangeInfo': 'Ändern Sie den Jackpot von 75 Millionen auf 10 Millionen Euro. Diese Änderung wird sofort auf der Hauptseite sichtbar.',
    'hero.worldJackpot': 'WORLD JACKPOT',
    'hero.winningChance': 'Gewinnchance 1 zu 140 Mio.',
    'hero.nextChance': 'Nächste Chance zu gewinnen',
    'sidebar.totalClasses': 'Insgesamt {count} Gewinnklassen',
    'admin.displayOverrides': 'Anzeige-Überschreibungen',
    'admin.manualTitle': 'Manuelle Überschrift',
    'admin.manualDate': 'Manuelles Datum',
    'admin.manualTime': 'Manuelle Zeit',
    'admin.save': 'Speichern',
    'admin.reset': 'Zurücksetzen',
    'admin.overrideNote': 'Hinweis: Diese Änderungen überschreiben die automatische Datum/Zeit-Anzeige auf der Hauptseite.',
    'admin.manualNumbers': 'Manuelle Zahlen (optional)',
    'admin.lastWinningNumbers': 'Letzte Gewinnzahlen',
    'admin.winnersByClass': 'Gewinner nach Klassen',
    'admin.overridesSavedSuccess': 'Anzeige-Überschreibungen erfolgreich gespeichert!',
    'admin.overridesSaveError': 'Fehler beim Speichern der Überschreibungen',
    'admin.overridesResetSuccess': 'Anzeige-Überschreibungen zurückgesetzt!',
    'admin.overridesResetError': 'Fehler beim Zurücksetzen',
    'footer.yourChance': 'World Jackpot - Ihre Chance auf den großen Gewinn',
    'footer.demoArea': 'World Jackpot - Demo Bereich',
    'footer.liveDrawings': 'World Jackpot - Live Ziehungen',
    'footer.winningResults': 'World Jackpot - Gewinnzahlen & Ergebnisse',
    'footer.adminDashboard': 'World Jackpot - Administrative Dashboard',
    'prizes.winningChance': 'Gewinnchance: {odds}',
    'drawing.cutoffInfo': 'Annahmeschluss: 19:00 Uhr',
    'drawing.cutoffDynamic': 'Annahmeschluss: {time} Uhr',
    'drawing.winnersPerClass': 'Gewinner nach Gewinnklassen',
    'admin.jackpotControl': 'Jackpot-Kontrolle',
    'admin.simulatedJackpot': 'Simulierter Jackpot',
    'admin.adminControlled': 'Von Admin kontrolliert',
    'admin.realJackpot': 'Echter Jackpot',
    'admin.percentRevenue': '40% der Einnahmen',
    'admin.displayedJackpot': 'Angezeigter Jackpot',
    'admin.editJackpot': 'Jackpot bearbeiten',
    'admin.editJackpotAmount': 'Jackpot-Betrag bearbeiten',
    'admin.newJackpotAmount': 'Neuer Jackpot-Betrag (€)',
    'admin.confirm': 'Bestätigen',
    'admin.cancel': 'Abbrechen',
    'admin.drawingControl': 'Ziehungs-Kontrolle',
    'admin.noDrawingPerformed': 'Keine Ziehung durchgeführt',
    'admin.drawingPending': 'Ziehung ausstehend',
    'admin.ready': 'Bereit',
    'admin.startDrawing': 'Ziehung starten',
    'admin.drawingInProgress': 'Ziehung läuft...',
    'admin.autoDrawing': 'Auto-Ziehung',
    'admin.automaticDrawing': 'Automatische Ziehung',
    'admin.nextDrawing': 'Nächste Ziehung',
    'admin.timeUntilDrawing': 'Zeit bis zur Ziehung:',
    'admin.recentTickets': 'Letzte Spielscheine',
    'admin.total': 'insgesamt',
    'admin.autoDrawingToggleSuccess': 'Auto-Ziehung {status}!',
    'admin.autoDrawingToggleError': 'Fehler beim Umschalten der Auto-Ziehung',
    'admin.activated': 'aktiviert',
    'admin.deactivated': 'deaktiviert',
    'form.loginRequired': 'Bitte melden Sie sich an, um Spielscheine abzugeben',
    'form.loginPrompt': 'Melden Sie sich an, um Spielscheine abzugeben',
    'form.accountBenefit': 'Mit einem Konto können Sie bis zu 10 Spielscheine pro Ziehung abgeben',
    'form.maxTicketsError': 'Maximal 10 Spielscheine pro Ziehung erlaubt',
    'form.completeTicketError': 'Bitte vervollständigen Sie mindestens einen Spielschein',
    'form.submitSuccess': '{count} Spielschein(e) erfolgreich abgegeben!',
    'form.submitError': 'Fehler beim Abgeben der Spielscheine',
    'form.ticketNumber': 'Spielschein {number}',
    'form.twoWorldNumbers': '2 aus 12 WorldZahlen',
    'form.ticketComplete': 'Schein vollständig',
    'form.addAnother': 'Weiteren Schein hinzufügen',
    'form.validTickets': 'Gültige Scheine: {valid} von {total}',
    'form.totalCost': 'Gesamtkosten: {cost}€',
    'form.submitting': 'Wird abgegeben...',
    'form.submitTickets': '{count} Schein(e) abgeben',
    'format.timeAt': 'um {time} Uhr',
    'admin.user': 'User:',
    'admin.winnerClass': 'Gewinner Kl.',
  },
  fr: {
    'nav.tickets': 'Billets',
    'nav.winningNumbers': 'Numéros Gagnants',
    'nav.myTickets': 'Mes Billets',
    'nav.help': 'Aide',
    'nav.login': 'Connexion',
    'nav.adminPanel': 'Panneau Admin',
    'nav.balance': 'Solde',
    'nav.connectWallet': 'Connecter Portefeuille',
    'hero.title': 'WorldJackpot',
    'hero.subtitle': 'Le jackpot de loterie mondial',
    'hero.currentJackpot': 'Jackpot Actuel',
    'hero.nextDrawing': 'Prochain Tirage',
    'hero.lastWinningNumbers': 'Derniers Numéros Gagnants',
    'hero.playNow': 'Jouer Maintenant',
    'form.title': 'Soumettre un Billet',
    'form.description': 'Choisissez 5 numéros de 1-50 et 2 WorldNumbers de 1-12',
    'sidebar.myStats': 'Mes Statistiques',
    'sidebar.activeTickets': 'Billets Actifs',
    'sidebar.maxTickets': 'Maximum de billets par tirage: 10',
    'sidebar.costPerTicket': 'Coût par billet: 2,00€',
    'sidebar.howToPlay': 'Comment Jouer',
    'sidebar.step1': 'Choisissez 5 numéros de 1-50',
    'sidebar.step2': 'Choisissez 2 WorldNumbers de 1-12',
    'sidebar.step3': 'Soumettez votre billet (2€ par jeu)',
    'sidebar.step4': 'Attendez le tirage',
    'sidebar.nextDrawing': 'Prochain Tirage',
    'sidebar.cutoffTime': 'Heure limite: 19h00',
    'sidebar.winningClasses': 'Classes de Prix',
    'sidebar.class': 'Classe',
    'sidebar.correct': 'Correct',
    'sidebar.moreClasses': '... et 7 autres classes',
    'sidebar.currentWinners': 'Gagnants Actuels',
    'sidebar.winners': 'Gagnants',
    'myTickets.title': 'Mes Billets',
    'myTickets.subtitle': 'Vos billets de loterie personnels et leur statut',
    'myTickets.totalTickets': 'Total Billets',
    'myTickets.winners': 'Gagnants',
    'myTickets.totalStake': 'Mise Totale',
    'myTickets.totalWinnings': 'Gains Totaux',
    'myTickets.ticketsFrom': 'Billets de',
    'myTickets.ticketsTotal': 'billets au total',
    'myTickets.ticketNumber': 'Billet #',
    'myTickets.mainNumbers': 'Numéros principaux',
    'myTickets.worldNumbers': 'World',
    'myTickets.winner': 'Gagnant!',
    'myTickets.noWin': 'Pas de gain',
    'myTickets.class': 'Classe',
    'myTickets.noTickets': 'Aucun billet disponible',
    'myTickets.noTicketsUser': 'Vous n\'avez encore acheté aucun billet.',
    'myTickets.noTicketsLogin': 'Veuillez vous connecter pour voir vos billets.',
    'myTickets.buyFirst': 'Acheter le premier billet',
    'myTickets.info.title': 'Informations sur les Billets',
    'myTickets.info.cost': 'Chaque billet coûte 2,00€',
    'myTickets.info.highlights': 'Les numéros verts sont des correspondances sur les billets gagnants',
    'myTickets.info.automatic': 'Les gains sont automatiquement crédités',
    'myTickets.info.limit': 'Maximum: 10 billets par tirage',
    'winningNumbers.title': 'Numéros Gagnants',
    'winningNumbers.subtitle': 'Numéros gagnants actuels et vos billets pour le tirage',
    'winningNumbers.currentJackpot': 'Jackpot Actuel',
    'winningNumbers.nextDrawing': 'Prochain Tirage',
    'winningNumbers.currentWinningNumbers': 'Numéros Gagnants Actuels',
    'winningNumbers.drawnOn': 'Tiré le',
    'winningNumbers.mainNumbers': 'Numéros Principaux',
    'winningNumbers.worldNumbers': 'Numéros World',
    'winningNumbers.winnersByClass': 'Gagnants par Classe de Prix',
    'winningNumbers.class': 'Classe',
    'winningNumbers.winners': 'Gagnants',
    'winningNumbers.noDrawing': 'Aucun tirage effectué encore',
    'winningNumbers.nextDrawingTime': 'Le prochain tirage aura lieu le:',
    'winningNumbers.fridayTime': 'Vendredi, 21h00',
    'winningNumbers.cutoffTime': 'Heure limite: 19h00',
    'winningNumbers.myTicketsForDrawing': 'Mes Billets pour le Tirage Actuel',
    'winningNumbers.ticketsForNext': 'billets pour le prochain tirage',
    'winningNumbers.noTicketsForDrawing': 'Aucun billet pour le tirage actuel',
    'winningNumbers.noTicketsForNext': 'Vous n\'avez pas encore acheté de billets pour le prochain tirage.',
    'winningNumbers.buyTicket': 'Acheter billet',
    'winningNumbers.active': 'Actif',
    'winningNumbers.loginPrompt': 'Veuillez vous connecter',
    'winningNumbers.loginToSeeTickets': 'Pour voir vos billets pour le tirage actuel, veuillez vous connecter.',
    'winningNumbers.toLogin': 'Se connecter',
    'admin.intelligentDrawing': 'Tirage Intelligent',
    'admin.intelligentDrawingDesc': 'Tirage optimisé pour minimiser les gagnants multiples',
    'admin.intelligentDrawingEnabled': 'Activé: Les combinaisons de numéros rares sont privilégiées',
    'admin.intelligentDrawingDisabled': 'Désactivé: Tirage aléatoire régulier',
    'admin.lastAnalysis': 'Dernière Analyse Intelligente',
    'admin.ticketsAnalyzed': 'billets analysés',
    'admin.selectedMainNumbers': 'Numéros Principaux Sélectionnés:',
    'admin.selectedWorldNumbers': 'Numéros World Sélectionnés:',
    'admin.rarestNumbers': 'Numéros les plus rares de l\'analyse',
    'admin.minimizedWinners': 'Minimise les gagnants potentiels',
    'admin.intelligentDrawingSuccess': 'Tirage intelligent effectué avec succès!',
    'auth.login': 'Connexion',
    'auth.register': 'S\'inscrire',
    'auth.email': 'Email',
    'auth.password': 'Mot de passe',
    'auth.confirmPassword': 'Confirmer le mot de passe',
    'auth.loggingIn': 'Connexion...',
    'auth.registering': 'Inscription...',
    'footer.subtitle': 'Le jackpot de loterie mondial avec les meilleures chances de gagner.',
    'common.mainNumbers': 'Numéros Principaux',
    'common.worldNumbers': 'World',
    'common.loading': 'Chargement...',
    'common.untilNextDrawing': 'jusqu\'au prochain tirage',
    'common.drawingOverdue': 'Tirage en retard',
    'common.euro': 'EURO',
    'common.fridayTime': 'Vendredi, 21h00',
    'common.winningClass': 'Classe Gagnante',
    'common.totalRevenue': 'Chiffre d\'Affaires Total',
    'common.everyFridayAt21': 'Chaque vendredi à 21h00',
    'common.autoDrawingEnabled': '✅ Le tirage automatique est activé. Les tirages ont lieu automatiquement chaque vendredi à 21h00.',
    'common.autoDrawingDisabled': '⏸️ Le tirage automatique est désactivé. Les tirages doivent être démarrés manuellement.',
    'form.fiveMainNumbers': '5 numéros principaux (1-50, séparés par des virgules)',
    'form.twoWorldNumbers': '2 numéros World (1-12, séparés par des virgules)',
    'form.manualNumbersError': 'Les numéros manuels doivent contenir 5 numéros principaux et 2 numéros world',
    'admin.jackpotChangeInfo': 'Changez le jackpot de 75 millions à 10 millions d\'euros. Ce changement sera immédiatement visible sur la page principale.',
    'hero.worldJackpot': 'WORLD JACKPOT',
    'hero.winningChance': 'Chance de gagner 1 sur 140 millions',
    'hero.nextChance': 'Prochaine chance de gagner',
    'sidebar.totalClasses': 'Total {count} classes de prix',
    'admin.displayOverrides': 'Remplacements d\'Affichage',
    'admin.manualTitle': 'Titre Manuel',
    'admin.manualDate': 'Date Manuelle',
    'admin.manualTime': 'Heure Manuelle',
    'admin.save': 'Sauvegarder',
    'admin.reset': 'Réinitialiser',
    'admin.overrideNote': 'Note: Ces changements remplaceront l\'affichage automatique de date/heure sur la page principale.',
    'admin.manualNumbers': 'Numéros manuels (optionnel)',
    'admin.lastWinningNumbers': 'Derniers Numéros Gagnants',
    'admin.winnersByClass': 'Gagnants par Classe',
    'admin.overridesSavedSuccess': 'Remplacements d\'affichage sauvegardés avec succès!',
    'admin.overridesSaveError': 'Erreur lors de la sauvegarde des remplacements',
    'admin.overridesResetSuccess': 'Remplacements d\'affichage réinitialisés!',
    'admin.overridesResetError': 'Erreur lors de la réinitialisation',
    'footer.yourChance': 'World Jackpot - Votre chance pour le gros lot',
    'footer.demoArea': 'World Jackpot - Zone Démo',
    'footer.liveDrawings': 'World Jackpot - Tirages en Direct',
    'footer.winningResults': 'World Jackpot - Numéros Gagnants & Résultats',
    'footer.adminDashboard': 'World Jackpot - Tableau de Bord Administratif',
    'prizes.winningChance': 'Chance de gagner: {odds}',
    'drawing.cutoffInfo': 'Heure limite: 19h00',
    'drawing.cutoffDynamic': 'Heure limite: {time}',
    'drawing.winnersPerClass': 'Gagnants par Classe de Prix',
    'admin.jackpotControl': 'Contrôle du Jackpot',
    'admin.simulatedJackpot': 'Jackpot Simulé',
    'admin.adminControlled': 'Contrôlé par l\'admin',
    'admin.realJackpot': 'Jackpot Réel',
    'admin.percentRevenue': '40% des revenus',
    'admin.displayedJackpot': 'Jackpot Affiché',
    'admin.editJackpot': 'Modifier le Jackpot',
    'admin.editJackpotAmount': 'Modifier le Montant du Jackpot',
    'admin.newJackpotAmount': 'Nouveau Montant du Jackpot (€)',
    'admin.confirm': 'Confirmer',
    'admin.cancel': 'Annuler',
    'admin.drawingControl': 'Contrôle du Tirage',
    'admin.noDrawingPerformed': 'Aucun tirage effectué',
    'admin.drawingPending': 'Tirage en attente',
    'admin.ready': 'Prêt',
    'admin.startDrawing': 'Démarrer le Tirage',
    'admin.drawingInProgress': 'Tirage en cours...',
    'admin.autoDrawing': 'Tirage Auto',
    'admin.automaticDrawing': 'Tirage Automatique',
    'admin.nextDrawing': 'Prochain Tirage',
    'admin.timeUntilDrawing': 'Temps jusqu\'au tirage:',
    'admin.recentTickets': 'Billets Récents',
    'admin.total': 'total',
    'admin.autoDrawingToggleSuccess': 'Tirage automatique {status}!',
    'admin.autoDrawingToggleError': 'Erreur lors du basculement du tirage automatique',
    'admin.activated': 'activé',
    'admin.deactivated': 'désactivé',
    'form.loginRequired': 'Veuillez vous connecter pour soumettre des billets de loterie',
    'form.loginPrompt': 'Connectez-vous pour soumettre des billets de loterie',
    'form.accountBenefit': 'Avec un compte, vous pouvez soumettre jusqu\'à 10 billets de loterie par tirage',
    'form.maxTicketsError': 'Maximum 10 billets de loterie par tirage autorisés',
    'form.completeTicketError': 'Veuillez compléter au moins un billet de loterie',
    'form.submitSuccess': '{count} billet(s) de loterie soumis avec succès!',
    'form.submitError': 'Erreur lors de la soumission des billets de loterie',
    'form.ticketNumber': 'Billet de Loterie {number}',
    'form.twoWorldNumbers': '2 sur 12 Numéros World',
    'form.ticketComplete': 'Billet complet',
    'form.addAnother': 'Ajouter un autre billet',
    'form.validTickets': 'Billets valides: {valid} sur {total}',
    'form.totalCost': 'Coût total: {cost}€',
    'form.submitting': 'Soumission...',
    'form.submitTickets': 'Soumettre {count} billet(s)',
    'format.timeAt': 'à {time}',
    'admin.user': 'Utilisateur:',
    'admin.winnerClass': 'Gagnant Cl.',
  },
  es: {
    'nav.tickets': 'Boletos',
    'nav.winningNumbers': 'Números Ganadores',
    'nav.myTickets': 'Mis Boletos',
    'nav.help': 'Ayuda',
    'nav.login': 'Iniciar Sesión',
    'nav.adminPanel': 'Panel Admin',
    'nav.balance': 'Saldo',
    'nav.connectWallet': 'Conectar Billetera',
    'hero.title': 'WorldJackpot',
    'hero.subtitle': 'El jackpot de lotería mundial',
    'hero.currentJackpot': 'Jackpot Actual',
    'hero.nextDrawing': 'Próximo Sorteo',
    'hero.lastWinningNumbers': 'Últimos Números Ganadores',
    'hero.playNow': 'Jugar Ahora',
    'form.title': 'Enviar Boleto',
    'form.description': 'Elija 5 números del 1-50 y 2 WorldNumbers del 1-12',
    'sidebar.myStats': 'Mis Estadísticas',
    'sidebar.activeTickets': 'Boletos Activos',
    'sidebar.maxTickets': 'Máximo de boletos por sorteo: 10',
    'sidebar.costPerTicket': 'Costo por boleto: 2,00€',
    'sidebar.howToPlay': 'Cómo Jugar',
    'sidebar.step1': 'Elija 5 números del 1-50',
    'sidebar.step2': 'Elija 2 WorldNumbers del 1-12',
    'sidebar.step3': 'Envíe su boleto (2€ por juego)',
    'sidebar.step4': 'Espere el sorteo',
    'sidebar.nextDrawing': 'Próximo Sorteo',
    'sidebar.cutoffTime': 'Hora límite: 19:00',
    'sidebar.winningClasses': 'Clases de Premio',
    'sidebar.class': 'Clase',
    'sidebar.correct': 'Correcto',
    'sidebar.moreClasses': '... y 7 clases más',
    'sidebar.currentWinners': 'Ganadores Actuales',
    'sidebar.winners': 'Ganadores',
    'myTickets.title': 'Mis Boletos',
    'myTickets.subtitle': 'Sus boletos de lotería personales y su estado',
    'myTickets.totalTickets': 'Total Boletos',
    'myTickets.winners': 'Ganadores',
    'myTickets.totalStake': 'Apuesta Total',
    'myTickets.totalWinnings': 'Ganancias Totales',
    'myTickets.ticketsFrom': 'Boletos de',
    'myTickets.ticketsTotal': 'boletos en total',
    'myTickets.ticketNumber': 'Boleto #',
    'myTickets.mainNumbers': 'Números principales',
    'myTickets.worldNumbers': 'World',
    'myTickets.winner': '¡Ganador!',
    'myTickets.noWin': 'Sin ganancia',
    'myTickets.class': 'Clase',
    'myTickets.noTickets': 'No hay boletos disponibles',
    'myTickets.noTicketsUser': 'Aún no has comprado ningún boleto.',
    'myTickets.noTicketsLogin': 'Inicia sesión para ver tus boletos.',
    'myTickets.buyFirst': 'Comprar primer boleto',
    'myTickets.info.title': 'Información de Boletos',
    'myTickets.info.cost': 'Cada boleto cuesta 2,00€',
    'myTickets.info.highlights': 'Los números verdes son coincidencias en boletos ganadores',
    'myTickets.info.automatic': 'Las ganancias se acreditan autom��ticamente',
    'myTickets.info.limit': 'Máximo: 10 boletos por sorteo',
    'winningNumbers.title': 'Números Ganadores',
    'winningNumbers.subtitle': 'Números ganadores actuales y sus boletos para el sorteo',
    'winningNumbers.currentJackpot': 'Jackpot Actual',
    'winningNumbers.nextDrawing': 'Próximo Sorteo',
    'winningNumbers.currentWinningNumbers': 'Números Ganadores Actuales',
    'winningNumbers.drawnOn': 'Sorteado el',
    'winningNumbers.mainNumbers': 'Números Principales',
    'winningNumbers.worldNumbers': 'Números World',
    'winningNumbers.winnersByClass': 'Ganadores por Clase de Premio',
    'winningNumbers.class': 'Clase',
    'winningNumbers.winners': 'Ganadores',
    'winningNumbers.noDrawing': 'Aún no se ha realizado ningún sorteo',
    'winningNumbers.nextDrawingTime': 'El próximo sorteo se realizará el:',
    'winningNumbers.fridayTime': 'Viernes, 21:00',
    'winningNumbers.cutoffTime': 'Hora límite: 19:00',
    'winningNumbers.myTicketsForDrawing': 'Mis Boletos para el Sorteo Actual',
    'winningNumbers.ticketsForNext': 'boletos para el próximo sorteo',
    'winningNumbers.noTicketsForDrawing': 'No hay boletos para el sorteo actual',
    'winningNumbers.noTicketsForNext': 'Aún no has comprado boletos para el próximo sorteo.',
    'winningNumbers.buyTicket': 'Comprar boleto',
    'winningNumbers.active': 'Activo',
    'winningNumbers.loginPrompt': 'Inicie sesión',
    'winningNumbers.loginToSeeTickets': 'Para ver sus boletos para el sorteo actual, inicie sesión.',
    'winningNumbers.toLogin': 'Iniciar sesión',
    'admin.intelligentDrawing': 'Sorteo Inteligente',
    'admin.intelligentDrawingDesc': 'Sorteo optimizado para minimizar múltiples ganadores',
    'admin.intelligentDrawingEnabled': 'Activado: Se prefieren combinaciones de números raros',
    'admin.intelligentDrawingDisabled': 'Desactivado: Sorteo aleatorio regular',
    'admin.lastAnalysis': 'Último Análisis Inteligente',
    'admin.ticketsAnalyzed': 'boletos analizados',
    'admin.selectedMainNumbers': 'Números Principales Seleccionados:',
    'admin.selectedWorldNumbers': 'Números World Seleccionados:',
    'admin.rarestNumbers': 'Números más raros del análisis',
    'admin.minimizedWinners': 'Minimiza ganadores potenciales',
    'admin.intelligentDrawingSuccess': '¡Sorteo inteligente realizado con éxito!',
    'auth.login': 'Iniciar Sesión',
    'auth.register': 'Registrarse',
    'auth.email': 'Email',
    'auth.password': 'Contraseña',
    'auth.confirmPassword': 'Confirmar Contraseña',
    'auth.loggingIn': 'Iniciando sesión...',
    'auth.registering': 'Registrando...',
    'footer.subtitle': 'El jackpot de lotería mundial con las mejores oportunidades de ganar.',
    'common.mainNumbers': 'Números Principales',
    'common.worldNumbers': 'World',
    'common.loading': 'Cargando...',
    'common.untilNextDrawing': 'hasta el próximo sorteo',
    'common.drawingOverdue': 'Sorteo retrasado',
    'common.euro': 'EURO',
    'common.fridayTime': 'Viernes, 21:00',
    'common.winningClass': 'Clase Ganadora',
    'common.totalRevenue': 'Ingresos Totales',
    'common.everyFridayAt21': 'Todos los viernes a las 21:00',
    'common.autoDrawingEnabled': '✅ El sorteo automático está activado. Los sorteos se realizan automáticamente todos los viernes a las 21:00.',
    'common.autoDrawingDisabled': '⏸️ El sorteo automático está desactivado. Los sorteos deben iniciarse manualmente.',
    'form.fiveMainNumbers': '5 números principales (1-50, separados por comas)',
    'form.twoWorldNumbers': '2 números World (1-12, separados por comas)',
    'form.manualNumbersError': 'Los números manuales deben contener 5 números principales y 2 números world',
    'admin.jackpotChangeInfo': 'Cambie el jackpot de 75 millones a 10 millones de euros. Este cambio será inmediatamente visible en la página principal.',
    'hero.worldJackpot': 'WORLD JACKPOT',
    'hero.winningChance': 'Probabilidad de ganar 1 en 140 millones',
    'hero.nextChance': 'Próxima oportunidad de ganar',
    'sidebar.totalClasses': 'Total {count} clases de premio',
    'admin.displayOverrides': 'Reemplazos de Pantalla',
    'admin.manualTitle': 'Título Manual',
    'admin.manualDate': 'Fecha Manual',
    'admin.manualTime': 'Hora Manual',
    'admin.save': 'Guardar',
    'admin.reset': 'Restablecer',
    'admin.overrideNote': 'Nota: Estos cambios reemplazarán la visualización automática de fecha/hora en la página principal.',
    'admin.manualNumbers': 'Números manuales (opcional)',
    'admin.lastWinningNumbers': 'Últimos Números Ganadores',
    'admin.winnersByClass': 'Ganadores por Clase',
    'admin.overridesSavedSuccess': '¡Reemplazos de pantalla guardados exitosamente!',
    'admin.overridesSaveError': 'Error al guardar los reemplazos',
    'admin.overridesResetSuccess': '¡Reemplazos de pantalla restablecidos!',
    'admin.overridesResetError': 'Error al restablecer',
    'footer.yourChance': 'World Jackpot - Su oportunidad para el gran premio',
    'footer.demoArea': 'World Jackpot - Área Demo',
    'footer.liveDrawings': 'World Jackpot - Sorteos en Vivo',
    'footer.winningResults': 'World Jackpot - Números Ganadores y Resultados',
    'footer.adminDashboard': 'World Jackpot - Panel Administrativo',
    'prizes.winningChance': 'Probabilidad de ganar: {odds}',
    'drawing.cutoffInfo': 'Hora límite: 19:00',
    'drawing.cutoffDynamic': 'Hora límite: {time}',
    'drawing.winnersPerClass': 'Ganadores por Clase de Premio',
    'admin.jackpotControl': 'Control del Jackpot',
    'admin.simulatedJackpot': 'Jackpot Simulado',
    'admin.adminControlled': 'Controlado por admin',
    'admin.realJackpot': 'Jackpot Real',
    'admin.percentRevenue': '40% de los ingresos',
    'admin.displayedJackpot': 'Jackpot Mostrado',
    'admin.editJackpot': 'Editar Jackpot',
    'admin.editJackpotAmount': 'Editar Monto del Jackpot',
    'admin.newJackpotAmount': 'Nuevo Monto del Jackpot (€)',
    'admin.confirm': 'Confirmar',
    'admin.cancel': 'Cancelar',
    'admin.drawingControl': 'Control del Sorteo',
    'admin.noDrawingPerformed': 'No se realizó sorteo',
    'admin.drawingPending': 'Sorteo pendiente',
    'admin.ready': 'Listo',
    'admin.startDrawing': 'Iniciar Sorteo',
    'admin.drawingInProgress': 'Sorteo en progreso...',
    'admin.autoDrawing': 'Sorteo Auto',
    'admin.automaticDrawing': 'Sorteo Automático',
    'admin.nextDrawing': 'Próximo Sorteo',
    'admin.timeUntilDrawing': 'Tiempo hasta el sorteo:',
    'admin.recentTickets': 'Boletos Recientes',
    'admin.total': 'total',
    'admin.autoDrawingToggleSuccess': '¡Sorteo automático {status}!',
    'admin.autoDrawingToggleError': 'Error al cambiar el sorteo automático',
    'admin.activated': 'activado',
    'admin.deactivated': 'desactivado',
    'form.loginRequired': 'Por favor inicie sesión para enviar boletos de lotería',
    'form.loginPrompt': 'Inicie sesión para enviar boletos de lotería',
    'form.accountBenefit': 'Con una cuenta puede enviar hasta 10 boletos de lotería por sorteo',
    'form.maxTicketsError': 'Máximo 10 boletos de lotería por sorteo permitidos',
    'form.completeTicketError': 'Por favor complete al menos un boleto de lotería',
    'form.submitSuccess': '¡{count} boleto(s) de lotería enviados exitosamente!',
    'form.submitError': 'Error al enviar boletos de lotería',
    'form.ticketNumber': 'Boleto de Lotería {number}',
    'form.twoWorldNumbers': '2 de 12 Números World',
    'form.ticketComplete': 'Boleto completo',
    'form.addAnother': 'Agregar otro boleto',
    'form.validTickets': 'Boletos válidos: {valid} de {total}',
    'form.totalCost': 'Costo total: {cost}€',
    'form.submitting': 'Enviando...',
    'form.submitTickets': 'Enviar {count} boleto(s)',
    'format.timeAt': 'a las {time}',
    'admin.user': 'Usuario:',
    'admin.winnerClass': 'Ganador Cl.',
  },
  it: {
    'nav.tickets': 'Biglietti',
    'nav.winningNumbers': 'Numeri Vincenti',
    'nav.myTickets': 'I Miei Biglietti',
    'nav.help': 'Aiuto',
    'nav.login': 'Accedi',
    'nav.adminPanel': 'Pannello Admin',
    'nav.balance': 'Saldo',
    'nav.connectWallet': 'Connetti Portafoglio',
    'hero.title': 'WorldJackpot',
    'hero.subtitle': 'Il jackpot della lotteria mondiale',
    'hero.currentJackpot': 'Jackpot Attuale',
    'hero.nextDrawing': 'Prossima Estrazione',
    'hero.lastWinningNumbers': 'Ultimi Numeri Vincenti',
    'hero.playNow': 'Gioca Ora',
    'form.title': 'Invia Biglietto',
    'form.description': 'Scegli 5 numeri da 1-50 e 2 WorldNumbers da 1-12',
    'sidebar.myStats': 'Le Mie Statistiche',
    'sidebar.activeTickets': 'Biglietti Attivi',
    'sidebar.maxTickets': 'Massimo biglietti per estrazione: 10',
    'sidebar.costPerTicket': 'Costo per biglietto: 2,00€',
    'sidebar.howToPlay': 'Come Giocare',
    'sidebar.step1': 'Scegli 5 numeri da 1-50',
    'sidebar.step2': 'Scegli 2 WorldNumbers da 1-12',
    'sidebar.step3': 'Invia il tuo biglietto (2€ per giocata)',
    'sidebar.step4': 'Aspetta l\'estrazione',
    'sidebar.nextDrawing': 'Prossima Estrazione',
    'sidebar.cutoffTime': 'Orario limite: 19:00',
    'sidebar.winningClasses': 'Classi di Premio',
    'sidebar.class': 'Classe',
    'sidebar.correct': 'Corretti',
    'sidebar.moreClasses': '... e 7 altre classi',
    'sidebar.currentWinners': 'Vincitori Attuali',
    'sidebar.winners': 'Vincitori',
    'myTickets.title': 'I Miei Biglietti',
    'myTickets.subtitle': 'I tuoi biglietti della lotteria personali e il loro stato',
    'myTickets.totalTickets': 'Biglietti Totali',
    'myTickets.winners': 'Vincitori',
    'myTickets.totalStake': 'Puntata Totale',
    'myTickets.totalWinnings': 'Vincite Totali',
    'myTickets.ticketsFrom': 'Biglietti da',
    'myTickets.ticketsTotal': 'biglietti in totale',
    'myTickets.ticketNumber': 'Biglietto #',
    'myTickets.mainNumbers': 'Numeri principali',
    'myTickets.worldNumbers': 'World',
    'myTickets.winner': 'Vincitore!',
    'myTickets.noWin': 'Nessuna vincita',
    'myTickets.class': 'Classe',
    'myTickets.noTickets': 'Nessun biglietto disponibile',
    'myTickets.noTicketsUser': 'Non hai ancora acquistato biglietti.',
    'myTickets.noTicketsLogin': 'Accedi per vedere i tuoi biglietti.',
    'myTickets.buyFirst': 'Acquista primo biglietto',
    'myTickets.info.title': 'Informazioni Biglietti',
    'myTickets.info.cost': 'Ogni biglietto costa 2,00���',
    'myTickets.info.highlights': 'I numeri verdi sono corrispondenze sui biglietti vincenti',
    'myTickets.info.automatic': 'Le vincite vengono accreditate automaticamente',
    'myTickets.info.limit': 'Massimo: 10 biglietti per estrazione',
    'winningNumbers.title': 'Numeri Vincenti',
    'winningNumbers.subtitle': 'Numeri vincenti attuali e i tuoi biglietti per l\'estrazione',
    'winningNumbers.currentJackpot': 'Jackpot Attuale',
    'winningNumbers.nextDrawing': 'Prossima Estrazione',
    'winningNumbers.currentWinningNumbers': 'Numeri Vincenti Attuali',
    'winningNumbers.drawnOn': 'Estratti il',
    'winningNumbers.mainNumbers': 'Numeri Principali',
    'winningNumbers.worldNumbers': 'Numeri World',
    'winningNumbers.winnersByClass': 'Vincitori per Classe di Premio',
    'winningNumbers.class': 'Classe',
    'winningNumbers.winners': 'Vincitori',
    'winningNumbers.noDrawing': 'Nessuna estrazione ancora eseguita',
    'winningNumbers.nextDrawingTime': 'La prossima estrazione si svolgerà il:',
    'winningNumbers.fridayTime': 'Venerdì, 21:00',
    'winningNumbers.cutoffTime': 'Orario limite: 19:00',
    'winningNumbers.myTicketsForDrawing': 'I Miei Biglietti per l\'Estrazione Attuale',
    'winningNumbers.ticketsForNext': 'biglietti per la prossima estrazione',
    'winningNumbers.noTicketsForDrawing': 'Nessun biglietto per l\'estrazione attuale',
    'winningNumbers.noTicketsForNext': 'Non hai ancora acquistato biglietti per la prossima estrazione.',
    'winningNumbers.buyTicket': 'Acquista biglietto',
    'winningNumbers.active': 'Attivo',
    'winningNumbers.loginPrompt': 'Effettua il login',
    'winningNumbers.loginToSeeTickets': 'Per vedere i tuoi biglietti per l\'estrazione attuale, effettua il login.',
    'winningNumbers.toLogin': 'Accedi',
    'admin.intelligentDrawing': 'Estrazione Intelligente',
    'admin.intelligentDrawingDesc': 'Estrazione ottimizzata per minimizzare vincitori multipli',
    'admin.intelligentDrawingEnabled': 'Attivato: Sono preferite combinazioni di numeri rari',
    'admin.intelligentDrawingDisabled': 'Disattivato: Estrazione casuale regolare',
    'admin.lastAnalysis': 'Ultima Analisi Intelligente',
    'admin.ticketsAnalyzed': 'biglietti analizzati',
    'admin.selectedMainNumbers': 'Numeri Principali Selezionati:',
    'admin.selectedWorldNumbers': 'Numeri World Selezionati:',
    'admin.rarestNumbers': 'Numeri più rari dall\'analisi',
    'admin.minimizedWinners': 'Minimizza vincitori potenziali',
    'admin.intelligentDrawingSuccess': 'Estrazione intelligente eseguita con successo!',
    'auth.login': 'Accedi',
    'auth.register': 'Registrati',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Conferma Password',
    'auth.loggingIn': 'Accesso...',
    'auth.registering': 'Registrazione...',
    'footer.subtitle': 'Il jackpot della lotteria mondiale con le migliori possibilità di vincita.',
    'common.mainNumbers': 'Numeri Principali',
    'common.worldNumbers': 'World',
    'common.loading': 'Caricamento...',
    'common.untilNextDrawing': 'fino alla prossima estrazione',
    'common.drawingOverdue': 'Estrazione in ritardo',
    'common.euro': 'EURO',
    'common.fridayTime': 'Venerdì, 21:00',
    'common.winningClass': 'Classe Vincente',
    'common.totalRevenue': 'Ricavi Totali',
    'common.everyFridayAt21': 'Ogni venerdì alle 21:00',
    'common.autoDrawingEnabled': '✅ L\'estrazione automatica è attivata. Le estrazioni avvengono automaticamente ogni venerdì alle 21:00.',
    'common.autoDrawingDisabled': '⏸️ L\'estrazione automatica è disattivata. Le estrazioni devono essere avviate manualmente.',
    'form.fiveMainNumbers': '5 numeri principali (1-50, separati da virgole)',
    'form.twoWorldNumbers': '2 numeri World (1-12, separati da virgole)',
    'form.manualNumbersError': 'I numeri manuali devono contenere 5 numeri principali e 2 numeri world',
    'admin.jackpotChangeInfo': 'Cambia il jackpot da 75 milioni a 10 milioni di euro. Questo cambiamento sarà immediatamente visibile sulla pagina principale.',
    'hero.worldJackpot': 'WORLD JACKPOT',
    'hero.winningChance': 'Probabilità di vincita 1 su 140 milioni',
    'hero.nextChance': 'Prossima opportunità di vincere',
    'sidebar.totalClasses': 'Totale {count} classi di premio',
    'admin.displayOverrides': 'Sostituzioni Display',
    'admin.manualTitle': 'Titolo Manuale',
    'admin.manualDate': 'Data Manuale',
    'admin.manualTime': 'Ora Manuale',
    'admin.save': 'Salva',
    'admin.reset': 'Ripristina',
    'admin.overrideNote': 'Nota: Questi cambiamenti sostituiranno la visualizzazione automatica di data/ora sulla pagina principale.',
    'admin.manualNumbers': 'Numeri manuali (opzionale)',
    'admin.lastWinningNumbers': 'Ultimi Numeri Vincenti',
    'admin.winnersByClass': 'Vincitori per Classe',
    'admin.overridesSavedSuccess': 'Sostituzioni display salvate con successo!',
    'admin.overridesSaveError': 'Errore nel salvare le sostituzioni',
    'admin.overridesResetSuccess': 'Sostituzioni display ripristinate!',
    'admin.overridesResetError': 'Errore nel ripristinare',
    'footer.yourChance': 'World Jackpot - La tua opportunità per la grande vincita',
    'footer.demoArea': 'World Jackpot - Area Demo',
    'footer.liveDrawings': 'World Jackpot - Estrazioni Live',
    'footer.winningResults': 'World Jackpot - Numeri Vincenti e Risultati',
    'footer.adminDashboard': 'World Jackpot - Dashboard Amministrativo',
    'prizes.winningChance': 'Probabilità di vincita: {odds}',
    'drawing.cutoffInfo': 'Orario limite: 19:00',
    'drawing.cutoffDynamic': 'Orario limite: {time}',
    'drawing.winnersPerClass': 'Vincitori per Classe di Premio',
    'admin.jackpotControl': 'Controllo Jackpot',
    'admin.simulatedJackpot': 'Jackpot Simulato',
    'admin.adminControlled': 'Controllato dall\'admin',
    'admin.realJackpot': 'Jackpot Reale',
    'admin.percentRevenue': '40% dei ricavi',
    'admin.displayedJackpot': 'Jackpot Visualizzato',
    'admin.editJackpot': 'Modifica Jackpot',
    'admin.editJackpotAmount': 'Modifica Importo Jackpot',
    'admin.newJackpotAmount': 'Nuovo Importo Jackpot (€)',
    'admin.confirm': 'Conferma',
    'admin.cancel': 'Annulla',
    'admin.drawingControl': 'Controllo Estrazione',
    'admin.noDrawingPerformed': 'Nessuna estrazione eseguita',
    'admin.drawingPending': 'Estrazione in sospeso',
    'admin.ready': 'Pronto',
    'admin.startDrawing': 'Inizia Estrazione',
    'admin.drawingInProgress': 'Estrazione in corso...',
    'admin.autoDrawing': 'Estrazione Auto',
    'admin.automaticDrawing': 'Estrazione Automatica',
    'admin.nextDrawing': 'Prossima Estrazione',
    'admin.timeUntilDrawing': 'Tempo fino all\'estrazione:',
    'admin.recentTickets': 'Biglietti Recenti',
    'admin.total': 'totale',
    'admin.autoDrawingToggleSuccess': 'Estrazione automatica {status}!',
    'admin.autoDrawingToggleError': 'Errore nel cambiare l\'estrazione automatica',
    'admin.activated': 'attivata',
    'admin.deactivated': 'disattivata',
    'form.loginRequired': 'Effettua il login per inviare biglietti della lotteria',
    'form.loginPrompt': 'Accedi per inviare biglietti della lotteria',
    'form.accountBenefit': 'Con un account puoi inviare fino a 10 biglietti della lotteria per estrazione',
    'form.maxTicketsError': 'Massimo 10 biglietti della lotteria per estrazione consentiti',
    'form.completeTicketError': 'Completa almeno un biglietto della lotteria',
    'form.submitSuccess': '{count} biglietto(i) della lotteria inviati con successo!',
    'form.submitError': 'Errore nell\'invio dei biglietti della lotteria',
    'form.ticketNumber': 'Biglietto della Lotteria {number}',
    'form.twoWorldNumbers': '2 su 12 Numeri World',
    'form.ticketComplete': 'Biglietto completo',
    'form.addAnother': 'Aggiungi un altro biglietto',
    'form.validTickets': 'Biglietti validi: {valid} su {total}',
    'form.totalCost': 'Costo totale: {cost}€',
    'form.submitting': 'Invio...',
    'form.submitTickets': 'Invia {count} biglietto(i)',
    'format.timeAt': 'alle {time}',
    'admin.user': 'Utente:',
    'admin.winnerClass': 'Vincitore Cl.',
  },
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    return savedLanguage && Object.keys(translations).includes(savedLanguage) ? savedLanguage : 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string, params?: Record<string, string | number>): string => {
    const langTranslations = translations[language];
    let translation = langTranslations?.[key] || key;

    if (params) {
      Object.entries(params).forEach(([param, value]) => {
        translation = translation.replace(`{${param}}`, String(value));
      });
    }

    return translation;
  };

  const value: LanguageContextType = {
    language,
    setLanguage,
    t,
  };

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};
